version: "3.8"

services:
  app:
    container_name: app
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - app
    ports:
      - "8881:8881"
      - "8882:8882"

  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:6.0-ubi8
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-data:/data/db
    networks:
      - app

  frontend:
    container_name: client
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - app
      - frontend

volumes:
  mongo-data:

networks:
  app:
    driver: bridge
  frontend: