// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0--rc2
// source: plantsapi/plants_api.proto

package plantsapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlantsAPI_GetExampleV1_FullMethodName = "/plantsapi.PlantsAPI/GetExampleV1"
)

// PlantsAPIClient is the client API for PlantsAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlantsAPIClient interface {
	GetExampleV1(ctx context.Context, in *GetExampleV1Request, opts ...grpc.CallOption) (*GetExampleV1Response, error)
}

type plantsAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewPlantsAPIClient(cc grpc.ClientConnInterface) PlantsAPIClient {
	return &plantsAPIClient{cc}
}

func (c *plantsAPIClient) GetExampleV1(ctx context.Context, in *GetExampleV1Request, opts ...grpc.CallOption) (*GetExampleV1Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExampleV1Response)
	err := c.cc.Invoke(ctx, PlantsAPI_GetExampleV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlantsAPIServer is the server API for PlantsAPI service.
// All implementations must embed UnimplementedPlantsAPIServer
// for forward compatibility.
type PlantsAPIServer interface {
	GetExampleV1(context.Context, *GetExampleV1Request) (*GetExampleV1Response, error)
	mustEmbedUnimplementedPlantsAPIServer()
}

// UnimplementedPlantsAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlantsAPIServer struct{}

func (UnimplementedPlantsAPIServer) GetExampleV1(context.Context, *GetExampleV1Request) (*GetExampleV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExampleV1 not implemented")
}
func (UnimplementedPlantsAPIServer) mustEmbedUnimplementedPlantsAPIServer() {}
func (UnimplementedPlantsAPIServer) testEmbeddedByValue()                   {}

// UnsafePlantsAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlantsAPIServer will
// result in compilation errors.
type UnsafePlantsAPIServer interface {
	mustEmbedUnimplementedPlantsAPIServer()
}

func RegisterPlantsAPIServer(s grpc.ServiceRegistrar, srv PlantsAPIServer) {
	// If the following call pancis, it indicates UnimplementedPlantsAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlantsAPI_ServiceDesc, srv)
}

func _PlantsAPI_GetExampleV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExampleV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlantsAPIServer).GetExampleV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlantsAPI_GetExampleV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlantsAPIServer).GetExampleV1(ctx, req.(*GetExampleV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

// PlantsAPI_ServiceDesc is the grpc.ServiceDesc for PlantsAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlantsAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plantsapi.PlantsAPI",
	HandlerType: (*PlantsAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExampleV1",
			Handler:    _PlantsAPI_GetExampleV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plantsapi/plants_api.proto",
}
