// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0--rc2
// source: plants/v1/plants.proto

package plants_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlantsAPI_GetExampleV1_FullMethodName             = "/plants.v1.PlantsAPI/GetExampleV1"
	PlantsAPI_GetPlantsWithCareRulesV1_FullMethodName = "/plants.v1.PlantsAPI/GetPlantsWithCareRulesV1"
	PlantsAPI_CreateNewCareRuleV1_FullMethodName      = "/plants.v1.PlantsAPI/CreateNewCareRuleV1"
	PlantsAPI_GetCareRuleV1_FullMethodName            = "/plants.v1.PlantsAPI/GetCareRuleV1"
	PlantsAPI_GetPlantsV1_FullMethodName              = "/plants.v1.PlantsAPI/GetPlantsV1"
	PlantsAPI_CreatePlantV1_FullMethodName            = "/plants.v1.PlantsAPI/CreatePlantV1"
)

// PlantsAPIClient is the client API for PlantsAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlantsAPIClient interface {
	GetExampleV1(ctx context.Context, in *GetExampleV1Request, opts ...grpc.CallOption) (*GetExampleV1Response, error)
	GetPlantsWithCareRulesV1(ctx context.Context, in *GetPlantsWithCareRulesV1Request, opts ...grpc.CallOption) (*GetPlantsWithCareRulesV1Response, error)
	CreateNewCareRuleV1(ctx context.Context, in *CreateNewCareRuleV1Request, opts ...grpc.CallOption) (*CreateNewCareRuleV1Response, error)
	GetCareRuleV1(ctx context.Context, in *GetCareRuleV1Request, opts ...grpc.CallOption) (*GetCareRuleV1Response, error)
	GetPlantsV1(ctx context.Context, in *GetPlantsV1Request, opts ...grpc.CallOption) (*GetPlantsV1Response, error)
	CreatePlantV1(ctx context.Context, in *CreatePlantV1Request, opts ...grpc.CallOption) (*CreatePlantV1Response, error)
}

type plantsAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewPlantsAPIClient(cc grpc.ClientConnInterface) PlantsAPIClient {
	return &plantsAPIClient{cc}
}

func (c *plantsAPIClient) GetExampleV1(ctx context.Context, in *GetExampleV1Request, opts ...grpc.CallOption) (*GetExampleV1Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExampleV1Response)
	err := c.cc.Invoke(ctx, PlantsAPI_GetExampleV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plantsAPIClient) GetPlantsWithCareRulesV1(ctx context.Context, in *GetPlantsWithCareRulesV1Request, opts ...grpc.CallOption) (*GetPlantsWithCareRulesV1Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlantsWithCareRulesV1Response)
	err := c.cc.Invoke(ctx, PlantsAPI_GetPlantsWithCareRulesV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plantsAPIClient) CreateNewCareRuleV1(ctx context.Context, in *CreateNewCareRuleV1Request, opts ...grpc.CallOption) (*CreateNewCareRuleV1Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNewCareRuleV1Response)
	err := c.cc.Invoke(ctx, PlantsAPI_CreateNewCareRuleV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plantsAPIClient) GetCareRuleV1(ctx context.Context, in *GetCareRuleV1Request, opts ...grpc.CallOption) (*GetCareRuleV1Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCareRuleV1Response)
	err := c.cc.Invoke(ctx, PlantsAPI_GetCareRuleV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plantsAPIClient) GetPlantsV1(ctx context.Context, in *GetPlantsV1Request, opts ...grpc.CallOption) (*GetPlantsV1Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlantsV1Response)
	err := c.cc.Invoke(ctx, PlantsAPI_GetPlantsV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plantsAPIClient) CreatePlantV1(ctx context.Context, in *CreatePlantV1Request, opts ...grpc.CallOption) (*CreatePlantV1Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePlantV1Response)
	err := c.cc.Invoke(ctx, PlantsAPI_CreatePlantV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlantsAPIServer is the server API for PlantsAPI service.
// All implementations must embed UnimplementedPlantsAPIServer
// for forward compatibility.
type PlantsAPIServer interface {
	GetExampleV1(context.Context, *GetExampleV1Request) (*GetExampleV1Response, error)
	GetPlantsWithCareRulesV1(context.Context, *GetPlantsWithCareRulesV1Request) (*GetPlantsWithCareRulesV1Response, error)
	CreateNewCareRuleV1(context.Context, *CreateNewCareRuleV1Request) (*CreateNewCareRuleV1Response, error)
	GetCareRuleV1(context.Context, *GetCareRuleV1Request) (*GetCareRuleV1Response, error)
	GetPlantsV1(context.Context, *GetPlantsV1Request) (*GetPlantsV1Response, error)
	CreatePlantV1(context.Context, *CreatePlantV1Request) (*CreatePlantV1Response, error)
	mustEmbedUnimplementedPlantsAPIServer()
}

// UnimplementedPlantsAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlantsAPIServer struct{}

func (UnimplementedPlantsAPIServer) GetExampleV1(context.Context, *GetExampleV1Request) (*GetExampleV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExampleV1 not implemented")
}
func (UnimplementedPlantsAPIServer) GetPlantsWithCareRulesV1(context.Context, *GetPlantsWithCareRulesV1Request) (*GetPlantsWithCareRulesV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlantsWithCareRulesV1 not implemented")
}
func (UnimplementedPlantsAPIServer) CreateNewCareRuleV1(context.Context, *CreateNewCareRuleV1Request) (*CreateNewCareRuleV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNewCareRuleV1 not implemented")
}
func (UnimplementedPlantsAPIServer) GetCareRuleV1(context.Context, *GetCareRuleV1Request) (*GetCareRuleV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCareRuleV1 not implemented")
}
func (UnimplementedPlantsAPIServer) GetPlantsV1(context.Context, *GetPlantsV1Request) (*GetPlantsV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlantsV1 not implemented")
}
func (UnimplementedPlantsAPIServer) CreatePlantV1(context.Context, *CreatePlantV1Request) (*CreatePlantV1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlantV1 not implemented")
}
func (UnimplementedPlantsAPIServer) mustEmbedUnimplementedPlantsAPIServer() {}
func (UnimplementedPlantsAPIServer) testEmbeddedByValue()                   {}

// UnsafePlantsAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlantsAPIServer will
// result in compilation errors.
type UnsafePlantsAPIServer interface {
	mustEmbedUnimplementedPlantsAPIServer()
}

func RegisterPlantsAPIServer(s grpc.ServiceRegistrar, srv PlantsAPIServer) {
	// If the following call pancis, it indicates UnimplementedPlantsAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlantsAPI_ServiceDesc, srv)
}

func _PlantsAPI_GetExampleV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExampleV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlantsAPIServer).GetExampleV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlantsAPI_GetExampleV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlantsAPIServer).GetExampleV1(ctx, req.(*GetExampleV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlantsAPI_GetPlantsWithCareRulesV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlantsWithCareRulesV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlantsAPIServer).GetPlantsWithCareRulesV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlantsAPI_GetPlantsWithCareRulesV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlantsAPIServer).GetPlantsWithCareRulesV1(ctx, req.(*GetPlantsWithCareRulesV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlantsAPI_CreateNewCareRuleV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewCareRuleV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlantsAPIServer).CreateNewCareRuleV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlantsAPI_CreateNewCareRuleV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlantsAPIServer).CreateNewCareRuleV1(ctx, req.(*CreateNewCareRuleV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlantsAPI_GetCareRuleV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCareRuleV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlantsAPIServer).GetCareRuleV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlantsAPI_GetCareRuleV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlantsAPIServer).GetCareRuleV1(ctx, req.(*GetCareRuleV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlantsAPI_GetPlantsV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlantsV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlantsAPIServer).GetPlantsV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlantsAPI_GetPlantsV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlantsAPIServer).GetPlantsV1(ctx, req.(*GetPlantsV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlantsAPI_CreatePlantV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlantV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlantsAPIServer).CreatePlantV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlantsAPI_CreatePlantV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlantsAPIServer).CreatePlantV1(ctx, req.(*CreatePlantV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

// PlantsAPI_ServiceDesc is the grpc.ServiceDesc for PlantsAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlantsAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plants.v1.PlantsAPI",
	HandlerType: (*PlantsAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExampleV1",
			Handler:    _PlantsAPI_GetExampleV1_Handler,
		},
		{
			MethodName: "GetPlantsWithCareRulesV1",
			Handler:    _PlantsAPI_GetPlantsWithCareRulesV1_Handler,
		},
		{
			MethodName: "CreateNewCareRuleV1",
			Handler:    _PlantsAPI_CreateNewCareRuleV1_Handler,
		},
		{
			MethodName: "GetCareRuleV1",
			Handler:    _PlantsAPI_GetCareRuleV1_Handler,
		},
		{
			MethodName: "GetPlantsV1",
			Handler:    _PlantsAPI_GetPlantsV1_Handler,
		},
		{
			MethodName: "CreatePlantV1",
			Handler:    _PlantsAPI_CreatePlantV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plants/v1/plants.proto",
}
